---
name: PR Checks for Devcontainer
on:
  pull_request:
    paths:
      - '.devcontainer/**'
      - '!.devcontainer/CHANGELOG.md'

concurrency:
  # For pull requests, cancel all currently-running jobs for this workflow
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Devcontainer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Devcontainer
        shell: bash
        run: |
          devcontainer build \
            --workspace-folder ${{ github.workspace }} \
            --cache-from ghcr.io/jhatler/jhatler-devcontainer
