---
name: PR Checks for LaTeX Container
on:
  pull_request:
    paths:
      - 'containers/latex/**'
      - '!containers/latex/CHANGELOG.md'

concurrency:
  # For pull requests, cancel all currently-running jobs for this workflow
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: Build LaTeX Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Container
        uses: ./.github/actions/container
        with:
          context: "{{defaultContext}}:containers/latex"
          platforms: linux/amd64
          push: false
          repository: ghcr.io/jhatler/latex
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
