---
name: PR Checks for LaTeX Devcontainer
on:
  pull_request:
    paths:
      - "devcontainers/latex/**"
      - "!devcontainers/latex/CHANGELOG.md"

concurrency:
  # For pull requests, cancel all currently-running jobs for this workflow
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: Build Devcontainer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Devcontainer
        uses: ./.github/actions/devcontainer
        with:
          workspace: ${{ github.workspace }}/devcontainers/latex
          platforms: linux/amd64
          push: false
          repository: ghcr.io/jhatler/latex-devcontainer
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
