name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Process Release
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest

      - name: Checkout
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v3

      - name: Set short git commit SHA
        if: ${{ steps.release.outputs.releases_created }}
        id: git
        shell: bash
        run: echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> "$GITHUB_OUTPUT"
