name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Process Release
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest

      - name: Checkout
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # jscpd:ignore-start
      - name: Publish LaTeX Container
        if: ${{ steps.release.outputs['containers/latex--release_created'] }}
        uses: ./.github/actions/container
        with:
          context: "{{defaultContext}}:containers/latex"
          platforms: linux/amd64
          push: true
          repository: ghcr.io/jhatler/latex
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          semver_major: ${{ steps.release.outputs['containers/latex--major'] }}
          semver_minor: ${{ steps.release.outputs['containers/latex--minor'] }}
          semver_patch: ${{ steps.release.outputs['containers/latex--patch'] }}
      # jscpd:ignore-end

      # jscpd:ignore-start
      - name: Publish Devcontainer
        if: ${{ steps.release.outputs['.devcontainer--release_created'] || steps.release.outputs['containers/latex--release_created'] }}
        uses: ./.github/actions/devcontainer
        with:
          workspace: ${{ github.workspace }}
          platforms: linux/amd64
          push: true
          repository: ghcr.io/jhatler/jhatler-devcontainer
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          semver_major: ${{ steps.release.outputs['containers/latex--major'] }}
          semver_minor: ${{ steps.release.outputs['containers/latex--minor'] }}
          semver_patch: ${{ steps.release.outputs['containers/latex--patch'] }}
      # jscpd:ignore-end
